import React from "react";
import "./Gist.css";
import Octicon from "react-octicon";

const Gist = ({ gist }) => {
  if (!gist) {
    return null; // Return null if the gist data is undefined
  }

  const { owner, commits_url, forks_url, comments_url, starred_url, created_at, updated_at } = gist;

  return (
    <div className="gist" data-testid="gist-component">
      <div className="gist-header">
        <div className="user-info">
          <img
            src={owner?.avatar_url || ""} // Handle undefined or null owner avatar URL
            alt={owner?.login || ""}
            className="user-avatar"
          />
          <h2>{owner?.login || "Unknown User"}</h2>
        </div>

        <div className="user-details">
          <div className="gist-links">
            {/* Display links using Octicon icons */}
            <a href={commits_url} target="_blank" rel="noreferrer">
              <Octicon name="file" />{" "}
              {gist.files && Object.keys(gist.files).length} Files
            </a>
            <a href={forks_url} target="_blank" rel="noreferrer">
              <Octicon name="repo-forked" /> {gist.forks} Forks
            </a>
            <a href={comments_url} target="_blank" rel="noreferrer">
              <Octicon name="comment" /> {gist.comments} Comments
            </a>
            <a href={starred_url} target="_blank" rel="noreferrer">
              <Octicon name="star" /> {gist.stars} Stars
            </a>
          </div>
        </div>
      </div>
      <div className="gist-meta">
        {/* Display creation date */}
        <p>Created at: {created_at ? new Date(created_at).toLocaleDateString() : "Unknown Date"}</p>
        <p style={{ marginLeft: "20px", color: "rgba(0,0,0,0.3)" }}>|</p>
        {/* Display last updated date */}
        <p style={{ marginLeft: "20px" }}>
          Last updated: {updated_at ? new Date(updated_at).toLocaleDateString() : "Unknown Date"}
        </p>
      </div>
      <div className="gist-heading">
        {/* Display the owner of the gist */}
        <p>Generated by: {owner?.login || "Unknown User"}</p>
      </div>
      <div className="gist-files">
        <p>Files:</p>
        <ul>
          {gist.files && Object.keys(gist.files).map((fileName) => (
            <li key={fileName}>
              <a
                href={gist.files[fileName]?.raw_url || ""}
                target="_blank"
                rel="noopener noreferrer"
              >
                <Octicon name="file" /> {fileName}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default Gist;
