import React from "react";
import "./Gist.css";
import Octicon from "react-octicon";

const Gist = ({ gist }) => {
  return (
    <div className="gist">
      <div className="gist-header">
        <div className="user-info">
          <img
            src={gist.owner.avatar_url}
            alt={gist.owner.login}
            className="user-avatar"
          />
          <h2>{gist.owner.login}</h2>
        </div>

        <div className="user-details">
          <div className="gist-links">
            <a href={gist.commits_url} target="_blank" rel="noreferrer">
              <Octicon name="file" />{" "}
              {gist.files && Object.keys(gist.files).length} Files
            </a>
            <a href={gist.forks_url} target="_blank" rel="noreferrer">
              <Octicon name="repo-forked" /> {gist.forks} Forks
            </a>
            <a href={gist.comments_url} target="_blank" rel="noreferrer">
              <Octicon name="comment" /> {gist.comments} Comments
            </a>
            <a href={gist.starred_url} target="_blank" rel="noreferrer">
              <Octicon name="star" /> {gist.stars} Stars
            </a>
          </div>
        </div>
      </div>
      <div className="gist-meta">
        <p>Created at: {new Date(gist.created_at).toLocaleDateString()}</p>
        <p style={{ marginLeft: "20px", color: "rgba(0,0,0,0.3)" }}>|</p>

        <p style={{ marginLeft: "20px" }}>
          Last updated: {new Date(gist.updated_at).toLocaleDateString()}
        </p>
      </div>
      <div className="gist-heading">
        <p>Generated by: {gist.owner.login}</p>
      </div>
      <div className="gist-files">
        <p>Files:</p>
        <ul>
          {Object.keys(gist.files).map((fileName) => (
            <li key={fileName}>
              <a
                href={gist.files[fileName].raw_url}
                target="_blank"
                rel="noopener noreferrer"
              >
                <Octicon name="file" /> {fileName}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default Gist;
